### ISSUE TITLE
generates the import error

### ISSUE THREAD

**Issue by vinayakumarr** [odashi/chainer_nmt#1]
ImportError: No module named 'chainer'
ls: cannot access sample_data/result/dev.hyp.????????: No such file or directory
ls: cannot access sample_data/result/test.hyp.????????: No such file or directory

check the attached image
![untitled](https://cloud.githubusercontent.com/assets/18217467/21080900/c72f563e-bfe0-11e6-9824-008bee3fa5fe.png)

**Comment by odashi** [comment]
These errors might be mainly caused by only the first import error.
Check your Python environment can access the Chainer.
